### ISSUE TITLE
kinect V1?

### ISSUE THREAD

**Issue by fromEternal** [marcojrfurtado/KinectAnimationStudio#1]
How to work with this for kinect V1?
Will it support for facial motion capture?

**Comment by marcojrfurtado** [comment]
Hi @6eye ,
Unfortunately there is no support for V1, nor for facial capture.
V1's API is different. I created this project because Autodesk MotionBuilder, at the time, only supported V1. It had a plug-in for that, and you could use it to generate FBX. 
I'm not sure if current versions of MotionBuilder still support V1, but that was definitely available in older versions.
